### ISSUE TITLE
You have requested a non-existent service notice in backoffice

### ISSUE THREAD

**Issue by muyncky** [MultiSafepay/prestashop-official#2] opened 2022-05-20 16:13 UTC
In development and staging with debugging mode we get this:

<img width="667" alt="image" src="https://user-images.githubusercontent.com/17008327/169568080-19037056-8827-4cb4-aa8c-0d4b89a0e229.png">

In production without debugging mode we get a 500.

These are the logs:

**PrestaShop logs** (`var/logs`)
```
./prod.log:[2022-05-20 17:03:13] request.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "You have requested a non-existent service "multisafepay.payment_option_service"." at /var/www/example/example.com/public/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php line 348 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException(code: 0): You have requested a non-existent service \"multisafepay.payment_option_service\". at /var/www/example/example.com/public/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:348)"} []

```

**Server logs**
```
./example.com.access.log:83.219.74.254 - - [20/May/2022:14:37:27 +0200] "GET /adminxxxxxxxx/index.php?controller=AdminModules&configure=multisafepayofficial&token=700085417bd3cb03b7fd8f1f71efbf28 HTTP/2.0" 500 495 "https://www.example.com/adminxxxxxxxx/index.php/improve/modules/manage?_token=EBNLuNIXao25jl6H3ZsJfMXJ8zEKr14CsuivalxpBnU" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36" "-" "www.example.com" 0.568
```

Module version: **5.4.2**

**Comment by danielcivit** [comment] 2022-05-20 16:44
Hello. Thanks for reach us.   You are reporting two different issues, let's go one by one.

1. The one in the screenshot, have been already found days ago. However the fix is not released yet. I think is related with a third party module, which is listed and active in your database, but files are not there anymore.

You can fix it immediately overwriting our module:

https://github.com/MultiSafepay/prestashop-official/blob/main/src/Services/SystemStatusService.php#L231-L238

And replacing those lines with the following code: 

```
        foreach ($installedModules as $installedModule) {
            $module = $this->module::getInstanceByName($installedModule['name']);
            if ($module) {
                $active = ((bool)$module->active ? "Enabled" : "Disabled");
                $activeModules['settings'][$module->id]['label'] = $module->displayName;
                $activeModules['settings'][$module->id]['value'] = "Version: $module->version. Status: $active. Author: $module->author.";
            }
        }
```

We plan to release a new version next week, including a fix for this error and other important new features. 

2. For the second error you are reporting, we don't have previous reports, and I am not able to reproduce it, even using the same PrestaShop version shown in the shared screenshot. It's says the application can't found a Symfony service. However, the service is there, and properly declared. 

https://github.com/MultiSafepay/prestashop-official/blob/main/config/services.yml#L22-L25

Could you fix the first one, clean cache, and check if this continue happening?

Thanks again.

**Comment by danielcivit** [comment] 2022-05-25 15:30
Hello @muyncky 

- We just release a new version of our module. Among with other improvements contains some changes to fix the first issue, the one reported in the screenshot. 

- About the other issue, the one related with the non existing service, could you update and let us know if this is solved at that moment. If not, since we can not reproduce the issue, could you write an email to support@multisafepay.com. That will create a ticket in our ticket system, we can share sensitive information, an find the reason behind that error. 

Thanks again for reach us and your report.

**Comment by danielcivit** [comment] 2022-08-31 14:23
Hello @muyncky.

I am closing this GitHub issue due inactivity. Please, feel free to reopen this ticket, or contact us via [support@multisafepay.com](mailto:support@multisafepay.com).

Thanks.

**Closed as completed by danielcivit** 2022-08-31 14:23 UTC
