### ISSUE TITLE
Error in hookActionSetInvoice function

### ISSUE THREAD

**Issue by mathieuhen** [MultiSafepay/prestashop-official#1] opened 2021-12-02 08:26 UTC
Hello,

I installed the plugin and I got an error in the function hookActionSetInvoice on these lines : 

$orderInvoice = OrderInvoice::getInvoiceByNumber($params['OrderInvoice']->id);
$orderInvoiceNumber = $orderInvoice->getInvoiceNumberFormatted($order->id_lang, $order->id_shop);

The error : 
Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getInvoiceNumberFormatted() on bool

We are on PS 1.7.7.3. 

I changed the line 
$orderInvoice = OrderInvoice::getInvoiceByNumber($params['OrderInvoice']->id);
by 
$orderInvoice = $params['OrderInvoice'];

And that is OK now. 

It seems logical because on the hook ActionSetInvoice in the class Order, the variables sent are 

$invoice_number = Hook::exec('actionSetInvoice', [
    get_class($this) => $this,
    get_class($order_invoice) => $order_invoice,
    'use_existing_payment' => (bool) $use_existing_payment,
]);

So the var 'OrderInvoice' is already an object 'OrderInvoice' so no need to refetch again the invoice by number, we already have it. 

Or I'm wrong ?

**Comment by danielcivit** [comment] 2021-12-02 08:46
Hello @mathieuhen 

Thanks for reporting this issue. 
I will be working to confirm this issue and after that I will get back to you with more information.

**Comment by mathieuhen** [comment] 2021-12-02 08:49
OK, thanks. 
There is no more error but it's not completely resolved. I realised now that the invoice ID sent to MSP is always : #FA000000. 

So I let you check how resolve that ;)

**Comment by danielcivit** [comment] 2021-12-03 10:00
Hello @mathieuhen.

Once again, thanks for reporting this issue.  

I am sorry to have delayed an answer during the day of yesterday. A [problem related to PrestaShop](https://github.com/PrestaShop/PrestaShop/issues/26838); was preventing me to install and execute a PrestaShop 1.7.7.3 version to confirm the problem in the same version. Fortunately they have resolved this.

In relation to your problem: I have not been able to reproduce the problem in a clean installation of PrestaShop 1.7.7.3 . For us this is working correctly. 

I wonder if some other module may be overwriting the "Order" or "OrderInvoice" object; or maybe some other module is executing actions on this hook; avoiding the invoice id being assigned to the Order. Or we might have some bug or use another hook. In any case; I would like to get to the bottom of this.

Please, could you open a ticket with us at integration@multisafepay.com with a reference to this [GitHub issue](https://github.com/MultiSafepay/prestashop-official/issues/1). I will retake this issue from there.  Being our system, we can ask you for a staging environment, while we keep sensitive information safe, and reproduce the error, and finally understand if we should adjust something in the plugin; or maybe it's due to some other conflict in your setup. 

I will be waiting your answer to continue my investigation.

**Comment by mathieuhen** [comment] 2021-12-07 13:55
Hello Daniel, 

sorry for the delay. I will open a ticket. 

Thanks,

**Comment by danielcivit** [comment] 2021-12-09 15:48
Thanks again for your report @mathieuhen.

I am closing this; since it was reported by you in [release 5.1.1.](https://github.com/MultiSafepay/prestashop-official/releases/tag/5.1.1)

**Closed as completed by danielcivit** 2021-12-09 15:48 UTC
